//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galen.CI.Azure.Sql.Sharding.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoggingMessageTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoggingMessageTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Galen.CI.Azure.Sql.Sharding.App.LoggingMessageTemplates", typeof(LoggingMessageTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping database {shardDatabaseName} on server {shardServerName} to {shardKeyType} key {shardKeyValue} in list map {mapName} using shard map manager database {databaseName} on server {serverName} unless it is already mapped..
        /// </summary>
        internal static string AddListMapShard {
            get {
                return ResourceManager.GetString("AddListMapShard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping shard {shardNumber:D2} as database {shardDatabaseName} on server {shardServerName} to {shardKeyType} range ({shardRangeLowValue},{shardRangeHighValue}) in range map {mapName} using shard map manager database {databaseName} on server {serverName} unless it is already mapped..
        /// </summary>
        internal static string AddRangeMapShard {
            get {
                return ResourceManager.GetString("AddRangeMapShard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating database {databaseName} on server {serverName} if it does not already exist..
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating database user {databaseUserName} in database {databaseName} using login {loginName} on server {serverName} if it does not already exist..
        /// </summary>
        internal static string CreateDatabaseUser {
            get {
                return ResourceManager.GetString("CreateDatabaseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating list shard map {shardMapName} with key type {shardKeyType} in database {databaseName} on server {serverName} if it does not already exist..
        /// </summary>
        internal static string CreateListShardMap {
            get {
                return ResourceManager.GetString("CreateListShardMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating range shard map {shardMapName} with key type {shardKeyType} in database {databaseName} on server {serverName} if it does not already exist..
        /// </summary>
        internal static string CreateRangeShardMap {
            get {
                return ResourceManager.GetString("CreateRangeShardMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating sql login {loginName} on server {serverName} if it does not already exist..
        /// </summary>
        internal static string CreateSqlLogin {
            get {
                return ResourceManager.GetString("CreateSqlLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating sql login for Windows account {loginName} on server {serverName} if it does not already exist..
        /// </summary>
        internal static string CreateSqlLoginFromWindowsAccount {
            get {
                return ResourceManager.GetString("CreateSqlLoginFromWindowsAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying shard map mangement schema to database {databaseName} on server {serverName} if it does not already exist..
        /// </summary>
        internal static string Deploy {
            get {
                return ResourceManager.GetString("Deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granting CONNECT to {databaseUserName} with db_datareader and db_datawriter role memberships for database {databaseName} on server {serverName}.
        /// </summary>
        internal static string GrantUserReadWritePermissions {
            get {
                return ResourceManager.GetString("GrantUserReadWritePermissions", resourceCulture);
            }
        }
    }
}
